### ISSUE TITLE
Investigate scb file encoding

### ISSUE THREAD

**Issue by JohnStrunk** [JohnStrunk/wahoo-results#19]
It appears that `.scb` files may use windows-1252 encoding, causing parsing errors when encountering certain characters.

Related to: JohnStrunk/events2dolphin#1

**Comment by dfeeley** [comment]
Example file (with names genericized) attached:
[E028.scb.TXT](https://github.com/JohnStrunk/wahoo-results/files/6750042/E028.scb.TXT)

**Comment by JohnStrunk** [comment]
Thank you!
