### ISSUE TITLE
Pychromecast is broken on Windows

### ISSUE THREAD

**Issue by JohnStrunk** [JohnStrunk/wahoo-results#208]
Versions of pychromecast 13.0.2 and later don't work on windows due to the lack of support for poll()
- home-assistant-libs/pychromecast#681

Potential fix:
- home-assistant-libs/pychromecast#690

**Comment by strunker** [comment]
Just so you know we fixed this issue it is currently sitting in a pull request and has been for the past two weeks.

**Comment by JohnStrunk** [comment]
@strunker When I noticed the problem, I was very happy to see that you already had a PR for it. Thanks!

**Comment by Untit1ed** [comment]
13.0.4, still seeing the issue. I understand there's a PR with a fix, but is there a workaround for the library users using the latest version?
